version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: psql
    environment:
      - POSTGRES_DB=TestDjangoDocker
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    
  web:
    build: .
    container_name: django
    command: gunicorn cbv.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.dev
    expose:
      - 8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - db
    
  nginx:
    restart: always
    build:
      context: ./nginxconfig
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "1337:80"
    depends_on:
      - web

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    hostname: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1

  kafka:
    image: wurstmeister/kafka
    container_name: wm_kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://192.20.10.2:29092
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_BROKER_ID: 001

    depends_on:
      - zookeeper


  kafka2:
    image: wurstmeister/kafka
    container_name: wm_kafka2
    ports:
      - "9093:9093"
      - "29093:29093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9093,OUTSIDE://192.20.10.2:29093
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_BROKER_ID: 002

    depends_on:
      - zookeeper


  kafka3:
    image: wurstmeister/kafka
    container_name: wm_kafka3
    ports:
      - "9094:9094"
      - "29094:29094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9094,OUTSIDE://192.20.10.2:29094
      KAFKA_LISTENERS: INSIDE://:9094,OUTSIDE://:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_BROKER_ID: 003

    depends_on:
      - zookeeper
  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    container_name: kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS : "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null
  
volumes:
  postgres_data:
  static_volume:
  media_volume: